Projeto/projeto_bd2/app_bd2/urls.py
from django.urls import path

from .views import clientes, dashboard, encarregados, lista_MaoDeObra, lista_faturas, ver_faturas, lista_saida, adicionar_mao_de_obra, registar_veiculo, listar_veiculos, listar_reparacoes
from . import views

app_name = 'app_bd2'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    # ---------- CLIENTES ----------------- #
    path('clientes/', clientes, name='clientes'),
    path('clientes/adicionar_cliente/', views.adicionar_cliente, name='adicionar_cliente'),
    path('clientes/<int:id>/ver_cliente/', views.ver_cliente, name='ver_cliente'),
    path('clientes/faturas', views.cliente_listar_faturas, name='cliente_listar_faturas'),

    # ---------- ENCARREGADOS ----------------- #
    path('encarregados/', encarregados, name='encarregados'),
    path('encarregados/adicionar_encarregado/', views.adicionar_encarregado, name='adicionar_encarregado'),
    path('encarregados/<int:id>/ver_encarregado/', views.ver_encarregado, name='ver_encarregado'),
    path('encarregados/<int:id_encarregado>/lista_reparacoes/', views.listar_encarregado_reparacoes, name='listar_encarregado_reparacoes'),
    path('encarregados/listar_encarregado_logado_reparacoes/', views.listar_encarregado_logado_reparacoes, name='listar_encarregado_logado_reparacoes'),
    path('encarregados/encarregado_concluir_reparacao/<int:id_restauro>/<int:mao_de_obra_id>/', views.encarregado_concluir_reparacao, name='encarregado_concluir_reparacao'),
   
    # ---------- FATURAS ----------------- #
    path('faturas/', lista_faturas, name='lista_faturas'),
    path('faturas/<int:id_faturas>/', ver_faturas, name='ver_faturas'),
    path('faturas/saida', lista_saida, name='lista_saida'),
    path('criar_fatura/<int:id_saida>/', views.criar_fatura, name='criar_fatura'),

    #------------------- MÃO DE OBRA ----------------------#
    path('mao_obra/', lista_MaoDeObra, name='lista_MaoDeObra'),
    path('mao-de-obra/<int:id_mao_de_obra>/', views.ver_mao_de_obra, name='ver_mao_de_obra'),
    path('mao_obra/adicionar', adicionar_mao_de_obra, name='adicionar_mao_de_obra'),
    path('mao_de_obra/<int:id_mao_de_obra>/editar/', views.editar_mao_de_obra, name='editar_mao_de_obra'),
    path('mao_de_obra/<int:id_mao_de_obra>/deletar/', views.deletar_mao_de_obra, name='deletar_mao_de_obra'),
    path('mao_de_obra/importar/', views.importar_mao_de_obra_json, name='importar_mao_de_obra_json'),
    path('mao_de_obra/exportar/', views.exportar_mao_de_obra_json, name='exportar_mao_de_obra_json'),

    #------------------- VEICULOS  ----------------------#
    path('veiculos/registar/', registar_veiculo, name='registar_veiculo'),
    path('veiculos/', listar_veiculos, name='listar_veiculos'),
    path('veiculos/ver/<int:id_veiculo>/', views.ver_veiculo, name='ver_veiculo'),
    path('veiculos/editar/<int:id_veiculo>/', views.editar_veiculo, name='editar_veiculo'),
    path('veiculo/eliminar/<int:id_veiculo>/', views.eliminar_veiculo, name='eliminar_veiculo'),
    path('get_veiculos_por_cliente/', views.get_veiculos_por_cliente, name='get_veiculos_por_cliente'),

    ##### REPARAÇÕES  #####
    path('reparacoes/', listar_reparacoes, name='listar_reparacoes'),
    path('reparacoes/<int:id>/', views.ver_reparacao, name='ver_reparacao'),  # URL para visualizar detalhes de uma reparação
    path('reparacoes/admin_criar_restauro/', views.admin_criar_restauro, name='admin_criar_restauro'),
    path('reparacoes/editar/<int:id_restauro>/', views.editar_reparacao, name='editar_reparacao'),
    path('reparacoes/eliminar/<int:id_restauro>/', views.eliminar_reparacao, name='eliminar_reparacao'),

]

Projeto/projeto_bd2/login_bd2/urls.py
from django.urls import path

from .views import dashboard, logout_view, LoginView

app_name = 'login_bd2'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),  
    path('logout/', logout_view, name='logout'),
]

Projeto/projeto_bd2/projeto_bd2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_bd2.urls')),  
    path('dashboard/', include('app_bd2.urls')), 
]

Projeto/projeto_bd2/app_bd2/forms/cliente.py
from django import forms
from django.contrib.auth.models import User

class ClienteForm(forms.ModelForm):
    nif = forms.CharField(max_length=9, required=False)
    telemovel = forms.CharField(max_length=12, required=False)
    endereco = forms.CharField(max_length=50, required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'nif', 'telemovel', 'endereco']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def save(self, commit=True):
        username = self.cleaned_data['username']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        nif = self.cleaned_data.get('nif')
        telemovel = self.cleaned_data.get('telemovel')
        endereco = self.cleaned_data.get('endereco')
        
        return {
            'username': username,
            'first_name': first_name,
            'last_name': last_name,
            'email': email,
            'password': password,
            'nif': nif,
            'telemovel': telemovel,
            'endereco': endereco,
        }

Projeto/projeto_bd2/app_bd2/forms/encarregados.py
from django import forms
from django.contrib.auth.models import User

class EncarregadoForm(forms.Form):
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    nif = forms.CharField(max_length=9, required=False)
    telemovel = forms.CharField(max_length=12, required=False)
    endereco = forms.CharField(max_length=50, required=False)
    especialidade = forms.ChoiceField(choices=[], required=True)

    def __init__(self, *args, **kwargs):
        especialidades = kwargs.pop('especialidades', [])
        super().__init__(*args, **kwargs)
        self.fields['especialidade'].choices = [(e[0], e[1]) for e in especialidades]

Projeto/projeto_bd2/app_bd2/views.py
from django.shortcuts import redirect, render
from django.shortcuts import render, get_object_or_404
from django.db import connection
from django.contrib.auth.decorators import login_required
from pymongo import MongoClient
from .forms.cliente import ClienteForm
from .forms.encarregados import EncarregadoForm
from .models import MaoDeObra, Marca, Veiculo
from datetime import datetime
import json
from django.core.paginator import Paginator
from django.contrib import messages
import json
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from decimal import Decimal
from django.core.serializers.json import DjangoJSONEncoder

client = MongoClient('localhost', 27017)
db = client['BD2'] 
veiculos_collection = db["veiculos"]

from django.db import connection
from django.shortcuts import render

def dashboard(request):

    cliente_id = request.user.id
    def execute_function(func_name, *args):
        with connection.cursor() as cursor:
            # Cria um placeholder para os argumentos
            args_placeholder = ', '.join(['%s'] * len(args))
            # Executa a função PostgreSQL com os argumentos
            cursor.execute(f"SELECT {func_name}({args_placeholder});", args)
            result = cursor.fetchone()
        return result[0] if result else 0

    # Chame as funções PostgreSQL
    total_faturas = execute_function('contar_faturas')
    total_reparacoes = execute_function('contar_reparacoes')
    total_clientes = execute_function('contar_clientes')
    total_encarregados = execute_function('contar_encarregados')
    total_veiculos = execute_function('contar_veiculos')
    total_faturas_por_cliente = execute_function('contar_faturas_por_cliente', cliente_id)
    total_restauros_por_usuario = execute_function('contar_restauros_por_usuario', cliente_id)
    # Renderize o template com os valores obtidos
    context = {
        'page_title': 'Dashboard',
        'total_faturas': total_faturas,
        'total_reparacoes': total_reparacoes,
        'total_clientes': total_clientes,
        'total_encarregados': total_encarregados,
        'total_veiculos': total_veiculos,
        'total_faturas_por_cliente': total_faturas_por_cliente,
        'total_restauros_por_usuario': total_restauros_por_usuario
    }
    
    return render(request, 'dashboard.html', context)


# ------------------------ CLIENTES -------------------------- #

def clientes(request):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel
                FROM usuarios 
                    JOIN auth_user ON usuarios.user_id = auth_user.id 
                    JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
                    JOIN auth_group ON auth_user_groups.group_id = auth_group.id
                WHERE auth_group.name = 'Cliente'
        """)
        resultados = cursor.fetchall()

    clientes = []

    for row in resultados:
        clientes.append({
            'id_usuarios': row[0],  
            'nome': row[1],
            'nif': row[2],
            'email': row[3],
            'telemovel': row[4],
        })

    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes, 'page_title': 'Lista de Clientes'})

def adicionar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            group_name = 'Cliente' 
            nif = form.cleaned_data.get('nif')
            telemovel = form.cleaned_data.get('telemovel')
            endereco = form.cleaned_data.get('endereco')

            with connection.cursor() as cursor:
                cursor.execute("CALL proc_inserir_cliente(%s, %s, %s, %s, %s, %s, %s, %s, %s);", 
                               [username, first_name, last_name, email, password, group_name, nif, telemovel, endereco])
            
            return redirect('app_bd2:clientes')  
    else:
        form = ClienteForm()
    
    return render(request, 'clientes/adicionar_cliente.html', {'form': form})

def ver_cliente(request, id):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT u.nome, u.nif, u.email, u.telemovel, u.endereco
            FROM usuarios u
            WHERE u.id_usuarios = %s
        """, [id])
        resultado = cursor.fetchone()
    
    if resultado:
        cliente = {
            'id': id,
            'nome': resultado[0],
            'nif': resultado[1],
            'email': resultado[2],
            'telemovel': resultado[3],
            'endereco': resultado[4],
        }
    else:
        return redirect('app_bd2:clientes')  

    if request.method == 'POST':
        if 'update' in request.POST:
            with connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE usuarios
                    SET nome = %s, nif = %s, email = %s, telemovel = %s, endereco = %s
                    WHERE id_usuarios = %s
                """, [
                    request.POST['nome'],
                    request.POST['nif'],
                    request.POST['email'],
                    request.POST['telemovel'],
                    request.POST['endereco'],
                    id
                ])
            return redirect('app_bd2:clientes')
        elif 'delete' in request.POST:
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM usuarios WHERE id_usuarios = %s", [id])
            return redirect('app_bd2:clientes')

    return render(request, 'clientes/ver_cliente.html', {'cliente': cliente, 'page_title': 'Ver Cliente'})

def get_clientes():
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel, usuarios.user_id
            FROM usuarios
            JOIN auth_user ON usuarios.id_usuarios = auth_user.id
            JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
            JOIN auth_group ON auth_user_groups.group_id = auth_group.id
            WHERE auth_group.name = 'Cliente'
        """)
        rows = cursor.fetchall()
        return [{'id': row[0], 'nome': row[1], 'nif': row[2], 'email': row[3], 'telemovel': row[4]} for row in rows]

# ------------------------ ENCARREGADOS -------------------------- #

def encarregados(request):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel
                FROM usuarios 
                    JOIN auth_user ON usuarios.user_id = auth_user.id 
                    JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
                    JOIN auth_group ON auth_user_groups.group_id = auth_group.id
                WHERE auth_group.name = 'Trabalhador'
        """)
        resultados = cursor.fetchall()

    encarregados = []

    for row in resultados:
        encarregados.append({
            'id_usuarios': row[0],  
            'nome': row[1],
            'nif': row[2],
            'email': row[3],
            'telemovel': row[4],
        })

    return render(request, 'encarregados/lista_encarregados.html', {'encarregados': encarregados, 'page_title': 'Lista de Encarregados'})

def adicionar_encarregado(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            cursor.execute("SELECT id_especialidade, nome FROM especialidades")
            especialidades = cursor.fetchall()

        form = EncarregadoForm(request.POST, especialidades=especialidades)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            group_name = 'Trabalhador'
            nif = form.cleaned_data.get('nif')
            telemovel = form.cleaned_data.get('telemovel')
            endereco = form.cleaned_data.get('endereco')
            especialidade_id = form.cleaned_data['especialidade']

            with connection.cursor() as cursor:
                cursor.execute("CALL proc_inserir_encarregado(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);", 
                               [username, first_name, last_name, email, password, group_name, nif, telemovel, endereco, especialidade_id])

            return redirect('app_bd2:encarregados')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT id_especialidade, nome FROM especialidades")
            especialidades = cursor.fetchall()

        form = EncarregadoForm(especialidades=especialidades)

    return render(request, 'encarregados/adicionar_encarregado.html', {'form': form})

def ver_encarregado(request, id):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT u.nome, u.nif, u.email, u.telemovel, u.endereco, e.id_especialidade, u.user_id
            FROM usuarios u
            LEFT JOIN especialidade_usuarios e ON u.id_usuarios = e.id_usuarios
            WHERE u.id_usuarios = %s
        """, [id])
        resultado = cursor.fetchone()
    
    if resultado:
        encarregado = {
            'id': id,

Projeto/projeto_bd2/app_bd2/templates/dashboard.html
{% extends "menu.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
{% if request.user.groups.all.0.name == "Administrador" %}
    <div class="container mt-5">
        <div class="row text-center">
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-primary">Clientes</h2>
                        <p class="display-4 text-primary font-weight-bold">{{ total_clientes }}</p>
                        <a href="{% url 'app_bd2:clientes' %}" class="btn btn-primary mt-3">Ver Clientes</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-success">Encarregados</h2>
                        <p class="display-4 text-success font-weight-bold">{{ total_encarregados }}</p>
                        <a href="{% url 'app_bd2:encarregados' %}" class="btn btn-success mt-3">Ver Encarregados</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-warning">Reparações</h2>
                        <p class="display-4 text-warning font-weight-bold">{{ total_reparacoes }}</p>
                        <a href="{% url 'app_bd2:listar_reparacoes' %}" class="btn btn-warning mt-3">Ver Reparações</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-danger">Faturas</h2>
                        <p class="display-4 text-danger font-weight-bold">{{ total_faturas }}</p>
                        <a href="{% url 'app_bd2:lista_faturas' %}" class="btn btn-danger mt-3">Ver Faturas</a>
                    </div>
                </div>
            </div>
            <!-- Novo campo para o número de veículos -->
            <div class="col-md-12 mb-4">
                <div class="card shadow-sm text-center">
                    <div class="card-body">
                        <h2 class="card-title text-info">Veículos</h2>
                        <p class="display-4 text-info font-weight-bold">{{ total_veiculos }}</p>
                        <a href="{% url 'app_bd2:listar_veiculos' %}" class="btn btn-info mt-3">Ver Veículos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% if request.user.groups.all.0.name == "Cliente" %}
        <div class="row text-center">
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-danger">Faturas</h2>
                        <p class="display-4 text-danger font-weight-bold">{{ total_faturas_por_cliente }}</p>
                        <a href="{% url 'app_bd2:cliente_listar_faturas' %}" class="btn btn-danger mt-3">Ver Faturas</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- Menu para Trabalhador -->
    {% if request.user.groups.all.0.name == "Trabalhador" %}
    <div class="row text-center">
        <div class="col-md-6 mb-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-warning">Reparações</h2>
                    <p class="display-4 text-warning font-weight-bold">{{ total_restauros_por_usuario }}</p>
                    <a href="{% url 'app_bd2:listar_encarregado_logado_reparacoes' %}" class="btn btn-warning mt-3">Ver Reparações</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

Projeto/projeto_bd2/app_bd2/templates/menu.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Minha Aplicação{% endblock %}</title>
    <style>
        .navbar-custom {
            display: flex;
            align-items: center;
            justify-content: space-between;
            height: 60px; /* Ajuste a altura conforme necessário */
        }
        .navbar-brand {
            flex: 1;
            text-align: center;
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
        }
        .user-info {
            bottom: 0;
            right: 0;
            padding: 10px;
            display: flex;
            align-items: center;
            width: 100%;
            border-top: 1px solid #e9ecef;
        }
        .user-info img {
            width: 40px;
            height: 40px;
            border-radius: 50%; /* Torna a imagem redonda */
            margin-right: 10px;
            object-fit: cover; /* Garante que a imagem preencha o espaço sem distorção */
        }
        .user-info span {
            color: white;
            font-size: 16px; /* Tamanho da fonte do nome do usuário */
        }
        /* Certifica-se de que o menu dropdown abre à direita */
.dropdown-menu {
    left: 0; /* Ajusta a posição horizontal do menu dropdown */
    right: auto; /* Garante que o menu não se sobreponha ao botão */
}

    </style>
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-dark border-right" id="sidebar-wrapper">
            <div class="sidebar-heading text-white">Menu</div>
            <div class="list-group list-group-flush">

                <!-- Menu para Administrador -->
                {% if request.user.groups.all.0.name == "Administrador" %}
                <a href="{% url 'app_bd2:dashboard' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-home"></i> Início</a>
                <a href="{% url 'app_bd2:listar_veiculos' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-car"></i> Veículos</a>
                <a href="{% url 'app_bd2:listar_reparacoes' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-tools"></i> Reparações</a>
                <a href="{% url 'app_bd2:clientes' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-users"></i> Clientes</a>
                <a href="{% url 'app_bd2:encarregados' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-user-tie"></i> Encarregados</a>
                <a href="{% url 'app_bd2:lista_faturas' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-file-invoice"></i> Faturas</a>
                <a href="{% url 'app_bd2:lista_MaoDeObra' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-handshake"></i> Mão de Obra</a>
                {% endif %}

                <!-- Menu para Cliente -->
                {% if request.user.groups.all.0.name == "Cliente" %}
                <a href="{% url 'app_bd2:dashboard' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-home"></i> Início</a>
                <a href="{% url 'app_bd2:cliente_listar_faturas' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-file-invoice"></i> Faturas</a>
                {% endif %}

                <!-- Menu para Trabalhador -->
                {% if request.user.groups.all.0.name == "Trabalhador" %}
                <a href="{% url 'app_bd2:dashboard' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-home"></i> Início</a>
                <a href="{% url 'app_bd2:listar_encarregado_logado_reparacoes' %}" class="list-group-item list-group-item-action bg-dark text-white"><i class="fas fa-tools"></i> Reparações</a>
                {% endif %}
                
                <div class="user-info d-flex align-items-center">
                    <img src="{% static 'img/avatar.jpg' %}" alt="Avatar">
                    <span class="ml-2">{{ request.user.first_name }}</span>

                    <a href="{% url 'login_bd2:logout' %}" class="btn btn-danger ml-auto">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-dark" id="menu-toggle"><i class="fas fa-bars"></i></button>
                <div class="navbar-brand">
                    <h3 class="m-0">{{ page_title }}</h3>
                </div>
            </nav>

            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Popper.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>


<!-- Bootstrap -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
</body>
</html>