Projeto/projeto_bd2/app_bd2/urls.py
from django.urls import path

from .views import clientes, dashboard, encarregados, lista_MaoDeObra, lista_faturas, ver_faturas, lista_saida, adicionar_mao_de_obra, registar_veiculo, listar_veiculos, listar_reparacoes
from . import views

app_name = 'app_bd2'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    # ---------- CLIENTES ----------------- #
    path('clientes/', clientes, name='clientes'),
    path('clientes/adicionar_cliente/', views.adicionar_cliente, name='adicionar_cliente'),
    path('clientes/<int:id>/ver_cliente/', views.ver_cliente, name='ver_cliente'),
    path('clientes/faturas', views.cliente_listar_faturas, name='cliente_listar_faturas'),

    # ---------- ENCARREGADOS ----------------- #
    path('encarregados/', encarregados, name='encarregados'),
    path('encarregados/adicionar_encarregado/', views.adicionar_encarregado, name='adicionar_encarregado'),
    path('encarregados/<int:id>/ver_encarregado/', views.ver_encarregado, name='ver_encarregado'),
    path('encarregados/<int:id_encarregado>/lista_reparacoes/', views.listar_encarregado_reparacoes, name='listar_encarregado_reparacoes'),
    path('encarregados/listar_encarregado_logado_reparacoes/', views.listar_encarregado_logado_reparacoes, name='listar_encarregado_logado_reparacoes'),
    path('encarregados/encarregado_concluir_reparacao/<int:id_restauro>/<int:mao_de_obra_id>/', views.encarregado_concluir_reparacao, name='encarregado_concluir_reparacao'),
   
    # ---------- FATURAS ----------------- #
    path('faturas/', lista_faturas, name='lista_faturas'),
    path('faturas/<int:id_faturas>/', ver_faturas, name='ver_faturas'),
    path('faturas/saida', lista_saida, name='lista_saida'),
    path('criar_fatura/<int:id_saida>/', views.criar_fatura, name='criar_fatura'),

    #------------------- MÃO DE OBRA ----------------------#
    path('mao_obra/', lista_MaoDeObra, name='lista_MaoDeObra'),
    path('mao-de-obra/<int:id_mao_de_obra>/', views.ver_mao_de_obra, name='ver_mao_de_obra'),
    path('mao_obra/adicionar', adicionar_mao_de_obra, name='adicionar_mao_de_obra'),
    path('mao_de_obra/<int:id_mao_de_obra>/editar/', views.editar_mao_de_obra, name='editar_mao_de_obra'),
    path('mao_de_obra/<int:id_mao_de_obra>/deletar/', views.deletar_mao_de_obra, name='deletar_mao_de_obra'),
    path('mao_de_obra/importar/', views.importar_mao_de_obra_json, name='importar_mao_de_obra_json'),
    path('mao_de_obra/exportar/', views.exportar_mao_de_obra_json, name='exportar_mao_de_obra_json'),

    #------------------- VEICULOS  ----------------------#
    path('veiculos/registar/', registar_veiculo, name='registar_veiculo'),
    path('veiculos/', listar_veiculos, name='listar_veiculos'),
    path('veiculos/ver/<int:id_veiculo>/', views.ver_veiculo, name='ver_veiculo'),
    path('veiculos/editar/<int:id_veiculo>/', views.editar_veiculo, name='editar_veiculo'),
    path('veiculo/eliminar/<int:id_veiculo>/', views.eliminar_veiculo, name='eliminar_veiculo'),
    path('get_veiculos_por_cliente/', views.get_veiculos_por_cliente, name='get_veiculos_por_cliente'),

    ##### REPARAÇÕES  #####
    path('reparacoes/', listar_reparacoes, name='listar_reparacoes'),
    path('reparacoes/<int:id>/', views.ver_reparacao, name='ver_reparacao'),  # URL para visualizar detalhes de uma reparação
    path('reparacoes/admin_criar_restauro/', views.admin_criar_restauro, name='admin_criar_restauro'),
    path('reparacoes/editar/<int:id_restauro>/', views.editar_reparacao, name='editar_reparacao'),
    path('reparacoes/eliminar/<int:id_restauro>/', views.eliminar_reparacao, name='eliminar_reparacao'),

]

Projeto/projeto_bd2/projeto_bd2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_bd2.urls')),  
    path('dashboard/', include('app_bd2.urls')), 
]

Projeto/projeto_bd2/app_bd2/forms/cliente.py
from django import forms
from django.contrib.auth.models import User

class ClienteForm(forms.ModelForm):
    nif = forms.CharField(max_length=9, required=False)
    telemovel = forms.CharField(max_length=12, required=False)
    endereco = forms.CharField(max_length=50, required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'nif', 'telemovel', 'endereco']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def save(self, commit=True):
        username = self.cleaned_data['username']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        nif = self.cleaned_data.get('nif')
        telemovel = self.cleaned_data.get('telemovel')
        endereco = self.cleaned_data.get('endereco')
        
        return {
            'username': username,
            'first_name': first_name,
            'last_name': last_name,
            'email': email,
            'password': password,
            'nif': nif,
            'telemovel': telemovel,
            'endereco': endereco,
        }

Projeto/projeto_bd2/app_bd2/forms/encarregados.py
from django import forms
from django.contrib.auth.models import User

class EncarregadoForm(forms.Form):
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    nif = forms.CharField(max_length=9, required=False)
    telemovel = forms.CharField(max_length=12, required=False)
    endereco = forms.CharField(max_length=50, required=False)
    especialidade = forms.ChoiceField(choices=[], required=True)

    def __init__(self, *args, **kwargs):
        especialidades = kwargs.pop('especialidades', [])
        super().__init__(*args, **kwargs)
        self.fields['especialidade'].choices = [(e[0], e[1]) for e in especialidades]

Projeto/projeto_bd2/app_bd2/views.py
from django.shortcuts import redirect, render
from django.shortcuts import render, get_object_or_404
from django.db import connection
from django.contrib.auth.decorators import login_required
from pymongo import MongoClient
from .forms.cliente import ClienteForm
from .forms.encarregados import EncarregadoForm
from .models import MaoDeObra, Marca, Veiculo
from datetime import datetime
import json
from django.core.paginator import Paginator
from django.contrib import messages
import json
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from decimal import Decimal
from django.core.serializers.json import DjangoJSONEncoder

client = MongoClient('localhost', 27017)
db = client['BD2'] 
veiculos_collection = db["veiculos"]

from django.db import connection
from django.shortcuts import render

def dashboard(request):

    cliente_id = request.user.id
    def execute_function(func_name, *args):
        with connection.cursor() as cursor:
            # Cria um placeholder para os argumentos
            args_placeholder = ', '.join(['%s'] * len(args))
            # Executa a função PostgreSQL com os argumentos
            cursor.execute(f"SELECT {func_name}({args_placeholder});", args)
            result = cursor.fetchone()
        return result[0] if result else 0

    # Chame as funções PostgreSQL
    total_faturas = execute_function('contar_faturas')
    total_reparacoes = execute_function('contar_reparacoes')
    total_clientes = execute_function('contar_clientes')
    total_encarregados = execute_function('contar_encarregados')
    total_veiculos = execute_function('contar_veiculos')
    total_faturas_por_cliente = execute_function('contar_faturas_por_cliente', cliente_id)
    total_restauros_por_usuario = execute_function('contar_restauros_por_usuario', cliente_id)
    # Renderize o template com os valores obtidos
    context = {
        'page_title': 'Dashboard',
        'total_faturas': total_faturas,
        'total_reparacoes': total_reparacoes,
        'total_clientes': total_clientes,
        'total_encarregados': total_encarregados,
        'total_veiculos': total_veiculos,
        'total_faturas_por_cliente': total_faturas_por_cliente,
        'total_restauros_por_usuario': total_restauros_por_usuario
    }
    
    return render(request, 'dashboard.html', context)


# ------------------------ CLIENTES -------------------------- #

def clientes(request):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel
                FROM usuarios 
                    JOIN auth_user ON usuarios.user_id = auth_user.id 
                    JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
                    JOIN auth_group ON auth_user_groups.group_id = auth_group.id
                WHERE auth_group.name = 'Cliente'
        """)
        resultados = cursor.fetchall()

    clientes = []

    for row in resultados:
        clientes.append({
            'id_usuarios': row[0],  
            'nome': row[1],
            'nif': row[2],
            'email': row[3],
            'telemovel': row[4],
        })

    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes, 'page_title': 'Lista de Clientes'})

def adicionar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            group_name = 'Cliente' 
            nif = form.cleaned_data.get('nif')
            telemovel = form.cleaned_data.get('telemovel')
            endereco = form.cleaned_data.get('endereco')

            with connection.cursor() as cursor:
                cursor.execute("CALL proc_inserir_cliente(%s, %s, %s, %s, %s, %s, %s, %s, %s);", 
                               [username, first_name, last_name, email, password, group_name, nif, telemovel, endereco])
            
            return redirect('app_bd2:clientes')  
    else:
        form = ClienteForm()
    
    return render(request, 'clientes/adicionar_cliente.html', {'form': form})

def ver_cliente(request, id):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT u.nome, u.nif, u.email, u.telemovel, u.endereco
            FROM usuarios u
            WHERE u.id_usuarios = %s
        """, [id])
        resultado = cursor.fetchone()
    
    if resultado:
        cliente = {
            'id': id,
            'nome': resultado[0],
            'nif': resultado[1],
            'email': resultado[2],
            'telemovel': resultado[3],
            'endereco': resultado[4],
        }
    else:
        return redirect('app_bd2:clientes')  

    if request.method == 'POST':
        if 'update' in request.POST:
            with connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE usuarios
                    SET nome = %s, nif = %s, email = %s, telemovel = %s, endereco = %s
                    WHERE id_usuarios = %s
                """, [
                    request.POST['nome'],
                    request.POST['nif'],
                    request.POST['email'],
                    request.POST['telemovel'],
                    request.POST['endereco'],
                    id
                ])
            return redirect('app_bd2:clientes')
        elif 'delete' in request.POST:
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM usuarios WHERE id_usuarios = %s", [id])
            return redirect('app_bd2:clientes')

    return render(request, 'clientes/ver_cliente.html', {'cliente': cliente, 'page_title': 'Ver Cliente'})

def get_clientes():
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel, usuarios.user_id
            FROM usuarios
            JOIN auth_user ON usuarios.id_usuarios = auth_user.id
            JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
            JOIN auth_group ON auth_user_groups.group_id = auth_group.id
            WHERE auth_group.name = 'Cliente'
        """)
        rows = cursor.fetchall()
        return [{'id': row[0], 'nome': row[1], 'nif': row[2], 'email': row[3], 'telemovel': row[4]} for row in rows]

# ------------------------ ENCARREGADOS -------------------------- #

def encarregados(request):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT usuarios.id_usuarios, usuarios.nome, usuarios.nif, usuarios.email, usuarios.telemovel
                FROM usuarios 
                    JOIN auth_user ON usuarios.user_id = auth_user.id 
                    JOIN auth_user_groups ON auth_user.id = auth_user_groups.user_id
                    JOIN auth_group ON auth_user_groups.group_id = auth_group.id
                WHERE auth_group.name = 'Trabalhador'
        """)
        resultados = cursor.fetchall()

    encarregados = []

    for row in resultados:
        encarregados.append({
            'id_usuarios': row[0],  
            'nome': row[1],
            'nif': row[2],
            'email': row[3],
            'telemovel': row[4],
        })

    return render(request, 'encarregados/lista_encarregados.html', {'encarregados': encarregados, 'page_title': 'Lista de Encarregados'})

def adicionar_encarregado(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            cursor.execute("SELECT id_especialidade, nome FROM especialidades")
            especialidades = cursor.fetchall()

        form = EncarregadoForm(request.POST, especialidades=especialidades)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            group_name = 'Trabalhador'
            nif = form.cleaned_data.get('nif')
            telemovel = form.cleaned_data.get('telemovel')
            endereco = form.cleaned_data.get('endereco')
            especialidade_id = form.cleaned_data['especialidade']

            with connection.cursor() as cursor:
                cursor.execute("CALL proc_inserir_encarregado(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);", 
                               [username, first_name, last_name, email, password, group_name, nif, telemovel, endereco, especialidade_id])

            return redirect('app_bd2:encarregados')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT id_especialidade, nome FROM especialidades")
            especialidades = cursor.fetchall()

        form = EncarregadoForm(especialidades=especialidades)

    return render(request, 'encarregados/adicionar_encarregado.html', {'form': form})

def ver_encarregado(request, id):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT u.nome, u.nif, u.email, u.telemovel, u.endereco, e.id_especialidade, u.user_id
            FROM usuarios u
            LEFT JOIN especialidade_usuarios e ON u.id_usuarios = e.id_usuarios
            WHERE u.id_usuarios = %s
        """, [id])
        resultado = cursor.fetchone()
    
    if resultado:
        encarregado = {
            'id': id,

Projeto/projeto_bd2/app_bd2/templates/faturas/lista_faturas.html
{% extends "menu.html" %}

{% block title %}Faturas - Minha Aplicação{% endblock %}

{% block content %}
<div class="clientes-table-container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-0">Lista de Faturas</h2>
        <a href="{% url 'app_bd2:lista_saida' %}" class="btn btn-warning">
            <i class="fas fa-file-invoice"></i> Gerar Fatura
        </a>
    </div>

    <form method="get" class="mb-3">
        <input type="text" name="search" class="form-control" placeholder="Pesquisar..." value="{{ search_query }}">
        <input type="hidden" name="sort_by" value="{{ sort_by }}">
        <input type="hidden" name="sort_order" value="asc">
    </form>

    <table class="table faturas-table faturas-table-bordered mt-3" id="faturasTable">
        <thead>
            <tr>
                <th>
                    <a href="?sort_by=id_faturas" class="sort-link">
                        Número da Fatura 
                        <i class="fas fa-sort fa-sort-up"></i>
                    </a>
                </th>
                <th>
                    <a href="?sort_by=data_emissao" class="sort-link">
                        Data de Emissão 
                        <i class="fas fa-sort fa-sort-up"></i>
                    </a>
                </th>
                <th>
                    <a href="?sort_by=valor_total" class="sort-link">
                        Valor Total 
                        <i class="fas fa-sort fa-sort-up"></i>
                    </a>
                </th>
                <th>
                    <a href="?sort_by=nome_cliente" class="sort-link">
                        Nome do Cliente 
                        <i class="fas fa-sort fa-sort-up"></i>
                    </a>
                </th>
                <th>
                    <a href="?sort_by=nif_cliente" class="sort-link">
                        NIF do Cliente 
                        <i class="fas fa-sort fa-sort-up"></i>
                    </a>
                </th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for fatura in page_obj %}
            <tr>
                <td>{{ fatura.id_faturas }}</td>
                <td>{{ fatura.data_emissao }}</td>
                <td>{{ fatura.valor_total }}</td>
                <td>{{ fatura.nome_cliente }}</td>
                <td>{{ fatura.nif_cliente }}</td>
                <td>
                    <a href="{% url 'app_bd2:ver_faturas' fatura.id_faturas %}" class="btn btn-info btn-icon">
                        <i class="fas fa-eye"></i> Ver Dados
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center">Nenhuma fatura encontrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginação -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if sort_by %}&sort_by={{ sort_by }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}

            <li class="page-item disabled"><span class="page-link">{{ page_obj.number }}</span></li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

Projeto/projeto_bd2/app_bd2/templates/faturas/lista_saida.html
{% extends "menu.html" %}

{% block title %}Faturas - Minha Aplicação{% endblock %}

{% block content %}
<div class="clientes-table-container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-0">Lista de Saidas</h2>
        <a href="{% url 'app_bd2:lista_faturas' %}" class="btn btn-danger">
            <i class="fas fa-arrow-left"></i> Voltar
        </a>
    </div>

    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Pesquisar dados das saidas">

    <table class="table faturas-table faturas-table-bordered mt-3" id="faturasTable">
        <thead>
            <tr>
                <th onclick="sortTable(0)">Número da Saida <i class="fas fa-sort" id="sortIcon0"></i></th>
                <th onclick="sortTable(1)">Data de Saida <i class="fas fa-sort" id="sortIcon1"></i></th>
                <th onclick="sortTable(2)">Nome do Cliente <i class="fas fa-sort" id="sortIcon2"></th>
                <th onclick="sortTable(3)">NIF do Cliente <i class="fas fa-sort" id="sortIcon3"></th>
                <th>Mão de Obra </th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for saida in saidas %}
            <tr>
                <td>{{ saida.id_saida }}</td>
                <td>{{ saida.data_saida}}</td>
                <td>{{ saida.nome_cliente }}</td>
                <td>{{ saida.nif_cliente }}</td>
                <td>
                    <ul style="margin-left: 10px;">
                        {% for mao in saida.mao_de_obra %}
                        <li>Tarefa: {{ mao.nome }}</li>
                        {% empty %}
                        <li>Não há mão de obra associada.</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a href="{% url 'app_bd2:criar_fatura' id_saida=saida.id_saida %}" class="btn btn-warning">
                        <i class="fas fa-file-invoice"></i> Gerar Fatura
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="text-center">Nenhuma fatura encontrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% block extra_scripts %}
<script>
    // Função para ordenar a tabela
    function sortTable(n) {
        var table = document.getElementById("faturasTable");
        var rows, switching, i, x, y, shouldSwitch, dir, switchCount = 0;
        var switchIcon = document.getElementById(`sortIcon${n}`);
        var dir = switchIcon.getAttribute("data-dir") === "asc" ? "desc" : "asc";
        var switching = true;
        
        // Remover a classe de direção anterior
        document.querySelectorAll('th i').forEach(icon => icon.classList.remove('fa-sort-up', 'fa-sort-down'));

        // Definir o ícone de ordenação atual
        switchIcon.classList.add(dir === "asc" ? 'fa-sort-up' : 'fa-sort-down');
        switchIcon.setAttribute("data-dir", dir);

        while (switching) {
            switching = false;
            rows = table.rows;
            
            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                
                if (dir === "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }
            
            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchCount++;
            }
        }
    }

    // Função para filtrar a tabela
    document.getElementById("searchInput").addEventListener("input", function() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toLowerCase();
        table = document.getElementById("faturasTable");
        tr = table.getElementsByTagName("tr");
        
        for (i = 1; i < tr.length; i++) {
            tr[i].style.display = "none";
            td = tr[i].getElementsByTagName("td");
            
            for (var j = 0; j < td.length; j++) {
                if (td[j]) {
                    txtValue = td[j].textContent || td[j].innerText;
                    if (txtValue.toLowerCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                        break;
                    }
                }
            }
        }
    });
</script>
{% endblock %}

{% endblock %}

Projeto/projeto_bd2/app_bd2/templates/faturas/ver_faturas.html
{% extends "menu.html" %}

{% block title %}Detalhes da Fatura{% endblock %}

{% block content %}

<div class="clientes-detalhes-container">
    <h2>Detalhes da Fatura</h2>
    <table class="table table-bordered">
        <tr>
            <th>ID da Fatura:</th>
            <td>{{ fatura.id_fatura }}</td>
        </tr>
        <tr>
            <th>Data de Emissão:</th>
            <td>{{ fatura.data_emissao|date:"d \d\e F \d\e Y, H:i" }}</td>
        </tr>
        <tr>
            <th>Nome do Cliente:</th>
            <td>{{ fatura.nome_cliente }}</td>
        </tr>
        <tr>
            <th>NIF do Cliente:</th>
            <td>{{ fatura.nif_cliente }}</td>
        </tr>
        <tr>
            <th>Email do Cliente:</th>
            <td>{{ fatura.email_cliente }}</td>
        </tr>
        <tr>
            <th>Matricula do Veiculo:</th>
            <td>{{ fatura.matricula }}</td>
        </tr>
        <tr>
            <th>Mão de Obra:</th>
            <td>
                <ul class="indent-list">
                    {% for mao in fatura.mao_de_obra %}
                    <li> <b>Tarefa:</b> {{ mao.nome }}, <b>Valor:</b> {{ mao.valor }}</li>
                    {% empty %}
                    <li>Não há mão de obra associada.</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <th>Valor Total:</th>
            <td>{{ fatura.valor_total }}</td>
        </tr>
    </table>
    {% if request.user.groups.all.0.name == "Administrador" %}
        <div class="text-center mt-4">
            <a href="{% url 'app_bd2:lista_faturas' %}" class="btn btn-danger">Voltar à Lista</a>
        </div>
    {% endif %}
    {% if request.user.groups.all.0.name == "Cliente" %}
    <div class="text-center mt-4">
        <a href="{% url 'app_bd2:cliente_listar_faturas' %}" class="btn btn-danger">Voltar à Lista</a>
    </div>
    {% endif %}
</div>
<style>
    .indent-list {
        margin-left: 10px; /* Adiciona a margem à esquerda */
        list-style-type: none; /* Remove os marcadores da lista, se necessário */
        padding-left: 0; /* Remove o padding padrão da lista */
    }
    .indent-list li {
        padding-left: 0; /* Remove o padding dos itens da lista, se necessário */
    }
</style>
{% endblock %}